Adding italian lanuguages and i18n fixes
MultiMote/niimblue pull request #50
Opened 2024-11-17 15:19 UTC by mlgtcode

* adding italian translation
* fixing translation errors in german translation
* adding missing iso language codes

2024-11-17 16:26 UTC, MultiMote requested changes
Thanks!
One fix is needed.
Please run `yarn sv-check` before creating pull request 🙂

2024-11-17 16:26 UTC, MultiMote commented on src/locale/index.ts
> +import { translation_de } from "./it";
Should be `import { translation_it } from "./it";`

2024-11-17 17:09 UTC, mlgtcode commented
> Please run `yarn sv-check` before creating pull request 🙂

Will setup a development environment asap :)

2024-11-17 17:10 UTC, MultiMote approved these changes

2024-11-17 17:11 UTC, merged

2024-11-18 05:16 UTC, MultiMote commented
@mlgtcode Language switcher is now broken on mobile.

https://github.com/user-attachments/assets/e69565a4-77ed-496b-ac24-dc4ca3f2cb36