feat: add QRCode feature
MultiMote/niimblue pull request #9
Opened 2024-08-29 10:10 UTC by xfqz86

2024-08-29 11:21 UTC, MultiMote requested changes
Hi! Thank you so much for your contribution!
Please make a few changes so I can accept your pull request.

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/lib/ImageEditor.svelte
> +        </button>
Move this to the ObjectPicker component please.

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/lib/ImageEditor.svelte
> +    ImageEditorUtils.addQrCode(fabricCanvas);
Move this to the onObjectPicked function.

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/lib/QRCodeParamsControls.svelte
> +    <select class="from-select" value={ecl} on:change={eclChange}>
Typo (must be class="form-select").

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/lib/QRCodeParamsControls.svelte
> +  <textarea class="qrcode-content" value={text} on:change={textChange} />
Add form-control class.

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/lib/QRCodeParamsControls.svelte
> +    width: 100%;
Remove (form-control is 100% width).

2024-08-29 11:21 UTC, MultiMote commented on niimblue/src/fabric-object/qrcode.class.ts
Is this intended to be so many typing check suppressions?

2024-08-29 14:21 UTC, MultiMote commented
Also, saving then loading labels not working (`Cannot read properties of undefined (reading 'fromObject')`).

2024-08-30 02:27 UTC, xfqz86 commented
> Also, saving then loading labels not working (`Cannot read properties of undefined (reading 'fromObject')`).

[607c3d3](https://github.com/MultiMote/niimblue/pull/9/commits/607c3d3924d560715bc4ca5f573514a59f92d8df) fixed

2024-08-30 04:54 UTC, MultiMote approved these changes

2024-08-30 04:57 UTC, merged